---
cfssl_url: https://github.com/cloudflare/cfssl/releases/download
cfssl_bin_dir: /tmp/cfssl
cfssl_workdir: /tmp/cfssl
cfssl_workdir_config: "{{ cfssl_workdir }}/config"
cfssl_workdir_certs: "{{ cfssl_workdir }}/certs"
cfssl_cluster_hosts: "{% for host in ansible_play_hosts %}{{ hostvars[host]['ansible_default_ipv4']['address'] }},{{ hostvars[host]['ansible_hostname'] }}{% if not loop.last %},{% endif %}{% endfor %},127.0.0.1,127.0.1.1"
