---
- name: create cfssl bin directory
  file:
    path: "{{ cfssl_bin_dir }}"
    state: directory
    mode: "0755"
  delegate_to: localhost
  run_once: yes

- name: get latest release of the public repository
  github_release:
    user: cloudflare
    repo: cfssl
    action: latest_release
  register: release
  delegate_to: localhost
  run_once: yes

- name: download cloudflare binaries to local storage
  get_url:
    url: "{{ cfssl_url }}/{{ release.tag }}/{{ item }}_{{ release.tag[1:] }}_linux_amd64"
    dest: "{{ cfssl_bin_dir }}/{{ item }}"
    mode: "0755"
  loop:
    - cfssl
    - cfssljson
  delegate_to: localhost
  run_once: yes
