---
- name: create etcd system files
  template:
    src: etcd.service.j2
    dest: /etc/systemd/system/etcd.service
    owner: etcd
    group: etcd
    mode: "0644"
  when: >
    ansible_service_mgr == "systemd" or
    ansible_service_mgr == "ansible"
  become: yes
